<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>LibreKO.Quests</AssemblyName>
    <RootNamespace>LibreKO.Quests</RootNamespace>
  </PropertyGroup>

</Project>
